import mongoose, { Schema } from "mongoose";

// MCQ Question schema (used for certification tests)
// We expect admins to provide many MCQs (100+), test runtime selects 60 random questions
const mcqQuestionSchema = new Schema({
  question: { type: String, required: true },
  options: [{ type: String, required: true }], // 4 options
  correctAnswer: { type: Number, required: true }, // Index of correct option (0-3)
  marks: { type: Number, default: 1 },
});


// Test Attempt schema - tracks user attempts
const testAttemptSchema = new Schema({
  testId: { type: Schema.Types.ObjectId, ref: "RoadmapTest", required: true },
  userId: { type: String, required: true },
  roadmapId: { type: String, required: true },
  
  // User's answers
  mcqAnswers: [{ type: Number }], // Array of selected option indices
  // shortAnswers removed for MCQ-only flow
  // Snapshot of MCQs served to user for this attempt (includes correctAnswer)
  mcqSnapshot: [{ type: Schema.Types.Mixed }],
  
  // Scoring (MCQ-only flow)
  mcqScore: { type: Number, default: 0 }, // Out of 60
  // short answer scoring removed
  totalScore: { type: Number, default: 0 }, // Out of 60
  percentage: { type: Number, default: 0 },
  passed: { type: Boolean, default: false }, // true if >= 60%
  
  // short answer scoring removed
  
  // Timestamps
  startedAt: { type: Date, default: Date.now },
  submittedAt: { type: Date },
  lastSavedAt: { type: Date },
  
  // Admin can allow retry
  canRetry: { type: Boolean, default: false },
});

// Main Roadmap Test schema
const roadmapTestSchema = new Schema({
  roadmapId: { type: String, required: true, unique: true },
  roadmapTitle: { type: String, required: true },
  
  // Test details - admin-provided questions (MCQ only)
  mcqQuestions: [mcqQuestionSchema],
  // short answer questions removed - MCQ-only

  // Test settings
  // Certification tests now: 60 MCQs, 60 minutes, pass >= 60%
  duration: { type: Number, default: 60 }, // 60 minutes
  totalMarks: { type: Number, default: 60 },
  passingPercentage: { type: Number, default: 60 },
  
  // Generated by Gemini
  generatedAt: { type: Date, default: Date.now },
  
  // Auto-expire after 4 days to regenerate fresh questions
  expiresAt: { 
    type: Date, 
    default: () => new Date(Date.now() + 4 * 24 * 60 * 60 * 1000) // 4 days from now
  },
  
  // Admin can regenerate test
  lastRegeneratedBy: { type: String },
  lastRegeneratedAt: { type: Date },
}, {
  timestamps: true,
});

// Indexes for efficient queries
// Note: `roadmapId` is already unique at field level; avoid duplicate index declarations
testAttemptSchema.index({ userId: 1, roadmapId: 1 });
testAttemptSchema.index({ testId: 1, userId: 1 });

// Clean up existing models to prevent OverwriteModelError
if (mongoose.models.RoadmapTest) {
  delete mongoose.models.RoadmapTest;
}
if (mongoose.models.TestAttempt) {
  delete mongoose.models.TestAttempt;
}

export const RoadmapTest = mongoose.models.RoadmapTest || mongoose.model("RoadmapTest", roadmapTestSchema);
export const TestAttempt = mongoose.models.TestAttempt || mongoose.model("TestAttempt", testAttemptSchema);
