/**
 * Purpose
 * -------
 * Two models for the Roadmap Certification Test feature:
 * - `RoadmapTest` — the admin-managed test definition for a roadmap topic.
 * - `TestAttempt` — a single user attempt against a RoadmapTest.
 *
 * Relationships
 * - `RoadmapTest.roadmapId` links to a Roadmap document (string key, not ObjectId)
 *   — one roadmap can have exactly one test (enforced by `unique: true`).
 * - `TestAttempt.testId` references RoadmapTest; `TestAttempt.userId` is a string
 *   reference to User.
 *
 * Business Rules
 * - Tests auto-expire 4 days after creation (`expiresAt`) to force regeneration
 *   of fresh questions and prevent question sets from circulating indefinitely.
 * - Admins can store 100+ MCQs in `mcqQuestions`; the route randomly selects 60
 *   for each attempt, stored in `mcqSnapshot` so results are reproducible.
 * - `passed` is true when `percentage >= passingPercentage` (default 60%).
 * - `canRetry` on a TestAttempt is set by an admin, not computed automatically,
 *   so retries are granted deliberately rather than on any automated condition.
 * - Compound indexes on `{ userId, roadmapId }` and `{ testId, userId }` support
 *   the common query pattern of "find this user's attempt for this roadmap."
 *
 * TODO: Move `mcqSnapshot` to a separate GridFS document or S3 object for
 * attempts with very large question sets — large arrays in MongoDB documents
 * have a 16 MB document size limit.
 */

import mongoose, { Schema } from "mongoose";

// MCQ Question schema (used for certification tests)
// We expect admins to provide many MCQs (100+), test runtime selects 60 random questions
const mcqQuestionSchema = new Schema({
  question: { type: String, required: true },
  options: [{ type: String, required: true }], // 4 options
  correctAnswer: { type: Number, required: true }, // Index of correct option (0-3)
  marks: { type: Number, default: 1 },
  explanation: { type: String },
});


// Test Attempt schema - tracks user attempts
const testAttemptSchema = new Schema({
  testId: { type: Schema.Types.ObjectId, ref: "RoadmapTest", required: true },
  userId: { type: String, required: true },
  roadmapId: { type: String, required: true },
  
  // User's answers
  mcqAnswers: [{ type: Number }], // Array of selected option indices
  // shortAnswers removed for MCQ-only flow
  // Snapshot of MCQs served to user for this attempt (includes correctAnswer)
  mcqSnapshot: [{ type: Schema.Types.Mixed }],
  
  // Scoring (MCQ-only flow)
  mcqScore: { type: Number, default: 0 }, // Out of 60
  // short answer scoring removed
  totalScore: { type: Number, default: 0 }, // Out of 60
  percentage: { type: Number, default: 0 },
  passed: { type: Boolean, default: false }, // true if >= 60%
  
  // short answer scoring removed
  
  // Timestamps
  startedAt: { type: Date, default: Date.now },
  submittedAt: { type: Date },
  lastSavedAt: { type: Date },
  
  // Admin can allow retry
  canRetry: { type: Boolean, default: false },
});

// Main Roadmap Test schema
const roadmapTestSchema = new Schema({
  roadmapId: { type: String, required: true, unique: true },
  roadmapTitle: { type: String, required: true },
  
  // Test details - admin-provided questions (MCQ only)
  mcqQuestions: [mcqQuestionSchema],
  // short answer questions removed - MCQ-only

  // Test settings
  // Certification tests now: 60 MCQs, 60 minutes, pass >= 60%
  duration: { type: Number, default: 60 }, // 60 minutes
  totalMarks: { type: Number, default: 60 },
  passingPercentage: { type: Number, default: 60 },
  
  // Generated by Gemini
  generatedAt: { type: Date, default: Date.now },
  
  // Auto-expire after 4 days to regenerate fresh questions
  expiresAt: { 
    type: Date, 
    default: () => new Date(Date.now() + 4 * 24 * 60 * 60 * 1000) // 4 days from now
  },
  
  // Admin can regenerate test
  lastRegeneratedBy: { type: String },
  lastRegeneratedAt: { type: Date },
}, {
  timestamps: true,
});

// Indexes for efficient queries
// Note: `roadmapId` is already unique at field level; avoid duplicate index declarations
testAttemptSchema.index({ userId: 1, roadmapId: 1 });
testAttemptSchema.index({ testId: 1, userId: 1 });

// Clean up existing models to prevent OverwriteModelError
if (mongoose.models.RoadmapTest) {
  delete mongoose.models.RoadmapTest;
}
if (mongoose.models.TestAttempt) {
  delete mongoose.models.TestAttempt;
}

export const RoadmapTest = mongoose.models.RoadmapTest || mongoose.model("RoadmapTest", roadmapTestSchema);
export const TestAttempt = mongoose.models.TestAttempt || mongoose.model("TestAttempt", testAttemptSchema);
